all :
	# propositions
	latex propositions
	bibtex propositions
	bibtex propositions
	latex propositions
	latex propositions
	pdflatex propositions
	# augustine
	latex augustine
	bibtex augustine
	bibtex augustine
	latex augustine
	latex augustine
	pdflatex augustine
	# rules
	latex rules
	bibtex rules
	bibtex rules
	latex rules
	latex rules
	pdflatex rules
	# clean-ish
	-rm *.aux *.bbl *.bcf *.blg *.log *.xml *.gz *.dvi

1 :
	latex propositions
	bibtex propositions
	bibtex propositions
	latex propositions
	latex propositions
	pdflatex propositions
	-rm *.aux *.bbl *.bcf *.blg *.log *.xml *.gz *.dvi

propositions :
	-latex propositions
	-bibtex propositions
	-bibtex propositions
	-latex propositions
	-latex propositions
	-pdflatex propositions
	-rm *.aux *.bbl *.bcf *.blg *.log *.xml *.gz *.dvi

2 :
	latex augustine
	bibtex augustine
	bibtex augustine
	latex augustine
	latex augustine
	pdflatex augustine
	-rm *.aux *.bbl *.bcf *.blg *.log *.xml *.gz *.dvi

augustine :
	latex augustine
	bibtex augustine
	bibtex augustine
	latex augustine
	latex augustine
	pdflatex augustine
	-rm *.aux *.bbl *.bcf *.blg *.log *.xml *.gz *.dvi

3 :
	latex rules
	bibtex rules
	bibtex rules
	latex rules
	latex rules
	pdflatex rules
	-rm *.aux *.bbl *.bcf *.blg *.log *.xml *.gz *.dvi

rules :
	latex rules
	bibtex rules
	bibtex rules
	latex rules
	latex rules
	pdflatex rules
	-rm *.aux *.bbl *.bcf *.blg *.log *.xml *.gz *.dvi

clean :
	-rm *.aux *.dvi *.bbl *.bcf *.blg *.log *.xml *.gz *.pdf

